# Generated by Django 3.2.4 on 2021-06-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_alter_advertimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
