# Generated by Django 3.2.4 on 2021-06-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0005_alter_advertimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='location',
            field=models.CharField(default='Glasgow,UK', max_length=300),
        ),
    ]
