# Generated by Django 3.2.4 on 2021-07-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0006_advert_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='uploaded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
