# Generated by Django 3.2.4 on 2021-07-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0007_advert_uploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adverts', models.ManyToManyField(to='adverts.Advert')),
            ],
        ),
    ]
